#!/usr/bin/env python3
"""
VermAMG interactive setup wizard.

Run this after cloning to create a run config by answering a few questions,
then optionally launch the pipeline with a clean, high-level live progress view
(one line per stage - not the full logs).

    python scripts/vermamg_init.py

No flags required. Everything is asked interactively.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

# ---------------------------------------------------------------------------
# Small input helpers
# ---------------------------------------------------------------------------

def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"  {prompt}{suffix}: ").strip()
    except EOFError:
        val = ""
    return val or default


def ask_choice(prompt: str, options: list[tuple[str, str]], default: str) -> str:
    print(f"\n  {prompt}")
    for key, label in options:
        print(f"     {key}) {label}")
    valid = {k for k, _ in options}
    while True:
        val = ask("Choose", default)
        if val in valid:
            return val
        print(f"     ! Please choose one of: {', '.join(sorted(valid))}")


def slugify(text: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", text.strip().lower()).strip("_")
    return s or "project"


def warn_if_missing(path: str, label: str) -> None:
    if path and not (Path(path).is_absolute() and Path(path).exists()
                     or (ROOT / path).exists()):
        print(f"     ! note: {label} not found yet ({path}) - make sure it exists before running.")


# ---------------------------------------------------------------------------
# Config text builder (readable YAML, schema v2)
# ---------------------------------------------------------------------------

def build_config_text(a: dict) -> str:
    live = a["data_source"] == "live"
    return f"""# Generated by scripts/vermamg_init.py
schema_version: 2

project:
  name: "{a['project_name']}"
  slug: "{a['project_slug']}"

sample:
  name: ""
  slug: ""

analysis:
  mode: {a['mode']}

environment:
  backend: {a['backend']}
  profile: {a['profile']}

run:
  label: "{a['run_label']}"
  root: "runs/{{project_slug}}/{{run_label}}"
  layout_version: 2
  resume_policy: skip_pass
  overwrite_policy: fail_if_outputs_exist
  import_policy: {"copy" if live else "reference"}

inputs:
  fasta: "{a['fasta']}"
  metadata_tsv: "{a['metadata_tsv']}"

input_intake:
  id_policy: preserve_first_token
  duplicate_policy: fail
  min_sequence_length: 1
  invalid_sequence_policy: fail

metadata:
  id_column: protein_id
  required: false
  strict_extra_rows: false

batching:
  enabled: true
  strategy: fixed_size
  batch_size: 128
  target_batches: 0
  max_sequences: 0
  batch_prefix: "{a['project_slug']}"

backend_jobs:
  dry_run: {"false" if live else "true"}
  submit_jobs: false
  emit_local_bundle: true
  emit_slurm_bundle: true
  plan_colabfold: true
  plan_foldseek: true
  local_threads: {a['threads']}

slurm:
  account: "{a['slurm_account']}"
  partition_cpu: "{a['slurm_cpu']}"
  partition_gpu: "{a['slurm_gpu']}"
  partition_debug: ""
  cpus_cpu: 8
  cpus_gpu: 10
  mem_cpu: "16G"
  mem_gpu: "32G"
  time_cpu: "12:00:00"
  time_gpu: "12:00:00"

colabfold:
  mode: {"live" if live else "precomputed"}
  query_pdb_dir: "{a['query_pdb_dir']}"
  collector_manifest: "{a['collector_manifest']}"
  score_json_dir: ""
  pae_json_dir: ""
  placeholder_confidence_policy: explicit_na_with_qc
  cmd: "{a['colabfold_cmd']}"
  dry_run: {"false" if live else "true"}

foldseek:
  mode: {"live" if live else "precomputed_all_hits"}
  pdb_all_hits: "{a['pdb_all_hits']}"
  afsp_all_hits: "{a['afsp_all_hits']}"
  id_map: "{a['id_map']}"
  threads: {a['threads']}

resources:
  java_bin: "{a['java_bin']}"
  p2rank_cmd: "{a['p2rank_cmd']}"
  p2rank_jar: "{a['p2rank_jar']}"
  foldseek_bin: "{a['foldseek_bin']}"
  pdb_foldseek_db: "{a['pdb_db']}"
  afsp_foldseek_db: "{a['afsp_db']}"

reference_materialization:
  method: full_atom_cache
  source_run_root: "{a['ref_source_run_root']}"
  overwrite: false
  guard_reference_atom_names: true
  allow_ca_only_diagnostic: false

stages:
  input_intake: true
  batch_plan: true
  backend_job_plan: true
  import_colabfold: true
  import_foldseek: true
  foldseek_search: {"true" if live else "false"}
  m06b_m07b: true
  m08: true
  m09: true
  p2rank: true
  m10a_d: true
  m10f_render: false
  m11: true
  m12: true
  m13: true
  m14: true
  interpretation_ready_export: true

p2rank:
  threads: {a['threads']}
  chunk_size: 64

safety:
  require_run_root_outputs_only: true
  stop_on_dirty_partial_output: true
"""


# ---------------------------------------------------------------------------
# Interactive questionnaire
# ---------------------------------------------------------------------------

DEMO = {
    "fasta": "examples/smoke_precomputed/data/proteins.faa",
    "query_pdb_dir": "examples/smoke_precomputed/data/query_pdbs",
    "collector_manifest": "examples/smoke_precomputed/data/foldseek/collector_manifest.tsv",
    "pdb_all_hits": "examples/smoke_precomputed/data/foldseek/pdb_all_hits.tsv",
    "afsp_all_hits": "examples/smoke_precomputed/data/foldseek/afsp_all_hits.tsv",
    "id_map": "examples/smoke_precomputed/data/foldseek/id_map.tsv",
    "ref_source_run_root": "examples/smoke_precomputed/data/reference_run_cache",
}


def questionnaire() -> dict:
    print("=" * 70)
    print("  VermAMG setup wizard")
    print("  Answer a few questions to generate a run config. Press Enter to")
    print("  accept the [default] shown in brackets.")
    print("=" * 70)

    a: dict = {}

    src = ask_choice(
        "What input do you want to run?",
        [
            ("1", "Bundled smoke demo (3 proteins, no data needed - great first run)"),
            ("2", "My own data, precomputed (I already have PDBs + Foldseek hits)"),
            ("3", "My own data, live (run ColabFold + Foldseek; needs GPU + databases)"),
        ],
        default="1",
    )
    a["data_source"] = {"1": "demo", "2": "precomputed", "3": "live"}[src]

    print()
    a["project_name"] = ask("Project name", "VermAMG Demo" if a["data_source"] == "demo" else "My VermAMG Project")
    a["project_slug"] = slugify(ask("Project slug (folder name)", slugify(a["project_name"])))
    a["run_label"] = ask("Run label (run identifier)",
                         "smoke_demo_v1" if a["data_source"] == "demo" else "run_v1")

    a["mode"] = "full"

    env = ask_choice(
        "Where will this run?",
        [("1", "Local machine / WSL (local_wsl)"), ("2", "HPC cluster (SLURM)")],
        default="1",
    )
    a["backend"] = "local" if env == "1" else "slurm"
    a["profile"] = "local_wsl" if env == "1" else "slurm"

    a["slurm_account"] = a["slurm_cpu"] = a["slurm_gpu"] = ""
    if a["backend"] == "slurm":
        a["slurm_account"] = ask("SLURM account", "")
        a["slurm_cpu"] = ask("SLURM CPU partition", "")
        a["slurm_gpu"] = ask("SLURM GPU partition", "")

    a["threads"] = ask("CPU threads for Foldseek/P2Rank", "4")

    # defaults
    a.update({
        "metadata_tsv": "", "colabfold_cmd": "colabfold_batch",
        "foldseek_bin": "", "pdb_db": "", "afsp_db": "",
        "java_bin": "java",
        "p2rank_cmd": "resources/tools/p2rank/current/prank",
        "p2rank_jar": "resources/tools/p2rank/current/bin/p2rank.jar",
    })

    if a["data_source"] == "demo":
        a.update(DEMO)
        print("\n  Using bundled smoke-demo data (no paths to enter).")
    elif a["data_source"] == "precomputed":
        print("\n  Point the wizard at YOUR precomputed inputs:")
        a["fasta"] = ask("FASTA file path", "inputs/my_proteins.faa")
        a["query_pdb_dir"] = ask("Directory of per-protein PDB files", "inputs/query_pdbs")
        a["collector_manifest"] = ask("Collector manifest TSV (run_id|pdb_path|confidence_score)", "inputs/collector_manifest.tsv")
        a["pdb_all_hits"] = ask("Foldseek-vs-PDB hits TSV", "inputs/pdb_all_hits.tsv")
        a["afsp_all_hits"] = ask("Foldseek-vs-AFSP hits TSV", "inputs/afsp_all_hits.tsv")
        a["id_map"] = ask("ID map TSV (run_id -> protein_id)", "inputs/id_map.tsv")
        a["ref_source_run_root"] = ask("Prior run root with materialized references "
                                       "(or use the demo cache)", DEMO["ref_source_run_root"])
        a["metadata_tsv"] = ask("Metadata TSV (optional)", "")
        a["p2rank_cmd"] = ask("P2Rank command", a["p2rank_cmd"])
        a["p2rank_jar"] = ask("P2Rank jar", a["p2rank_jar"])
        a["java_bin"] = ask("java binary", a["java_bin"])
        for p, lbl in [(a["fasta"], "FASTA"), (a["query_pdb_dir"], "query_pdb_dir"),
                       (a["collector_manifest"], "collector_manifest")]:
            warn_if_missing(p, lbl)
    else:  # live
        print("\n  Live mode runs ColabFold + Foldseek from your FASTA (needs GPU + DBs):")
        a["fasta"] = ask("FASTA file path", "inputs/my_proteins.faa")
        a["query_pdb_dir"] = ""
        a["collector_manifest"] = ""
        a["pdb_all_hits"] = a["afsp_all_hits"] = a["id_map"] = ""
        a["ref_source_run_root"] = ask("Prior run root with materialized references (optional)", "")
        a["colabfold_cmd"] = ask("ColabFold command", a["colabfold_cmd"])
        a["foldseek_bin"] = ask("Foldseek binary", "resources/tools/foldseek/bin/foldseek")
        a["pdb_db"] = ask("Foldseek PDB database", "resources/databases/foldseek/pdb/pdb")
        a["afsp_db"] = ask("Foldseek AFSP database", "resources/databases/foldseek/alphafold_swissprot/af_swissprot")
        a["p2rank_cmd"] = ask("P2Rank command", a["p2rank_cmd"])
        a["p2rank_jar"] = ask("P2Rank jar", a["p2rank_jar"])
        warn_if_missing(a["fasta"], "FASTA")

    return a


# ---------------------------------------------------------------------------
# Live high-level progress (polls state/status.json - no verbose logs)
# ---------------------------------------------------------------------------

def run_with_progress(config_path: Path) -> int:
    from vermamg_lib.config import load_run_config
    from vermamg_lib.run_context import RunContext
    from vermamg_lib.stage_registry import build_stages
    from vermamg_lib.state import read_status

    cfg = load_run_config(config_path)
    ctx = RunContext.from_config(config_path, cfg)
    stages = [s for s in build_stages(ctx) if s.enabled(ctx)]
    order = [s.stage_id for s in stages]
    titles = {s.stage_id: s.title for s in stages}
    total = len(stages)

    print("\n" + "=" * 70)
    print(f"  Running: {ctx.project_name} / {ctx.run_label}   ({total} stages)")
    print(f"  Run dir: {ctx.rel_to_project(ctx.run_root)}")
    print("  Live progress (one line per stage; full logs in the run dir):")
    print("=" * 70)

    done: set[str] = set()
    running_shown: str | None = None

    def mark_done_through(stage_id: str) -> None:
        if stage_id not in order:
            return
        for sid in order[: order.index(stage_id) + 1]:
            if sid not in done:
                done.add(sid)
                print(f"  [OK] [{len(done):>2}/{total}] {titles.get(sid, sid)}")

    log_dir = ROOT / "logs"
    log_dir.mkdir(exist_ok=True)
    run_log = log_dir / f"wizard_run_{ctx.run_label}.log"

    with run_log.open("w", encoding="utf-8") as logf:
        proc = subprocess.Popen(
            [sys.executable, str(ROOT / "scripts" / "vermamg.py"),
             "run", "--config", str(config_path), "--resume"],
            cwd=str(ROOT), stdout=logf, stderr=subprocess.STDOUT,
        )
        while True:
            st = read_status(ctx.run_root) or {}
            lps = st.get("last_pass_stage", "")
            cur = st.get("current_stage", "")
            if lps:
                mark_done_through(lps)
            if cur and cur not in done and cur != running_shown:
                running_shown = cur
                print(f"  >> [{len(done) + 1:>2}/{total}] {titles.get(cur, cur)} ...", flush=True)
            if proc.poll() is not None:
                break
            time.sleep(0.6)

    st = read_status(ctx.run_root) or {}
    if lps := st.get("last_pass_stage", ""):
        mark_done_through(lps)
    final = st.get("status", "UNKNOWN")
    print("=" * 70)
    if proc.returncode == 0:
        print(f"  [OK] DONE - {final}.  Exports under: {ctx.rel_to_project(ctx.run_root)}/exports/")
    else:
        cur = st.get("current_stage", "")
        where = titles.get(cur, cur) if cur else "setup / validation (before the first stage)"
        print(f"  [X] STOPPED at: {where}  (status={final})")
        for err in (st.get("validation_errors") or [])[:6]:
            print(f"    - {err}")
        markers = ("RUNTIME_ENVIRONMENT_ERROR", "MISSING_STAGE_INPUT", "RUN_EXECUTION_ERROR",
                   "CONFIG_ERROR", "EXCEPTION")
        try:
            lines = run_log.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            lines = []
        for ln in [l for l in lines if any(m in l for m in markers)][-8:]:
            print(f"    | {ln.strip()[:120]}")
        print(f"    Full run log: {run_log.relative_to(ROOT)}")
        if st.get("latest_log"):
            print(f"    Stage log:    {st['latest_log']}")
        print("    Tip: fix the issue and re-run - it resumes from the last PASS.")
    print("=" * 70)
    return proc.returncode


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

TEMPLATES = {
    "local": "run_templates/local_run.yaml.template",
    "slurm": "run_templates/hpc_slurm_run_v2.yaml.template",
}


def offer_plan_or_run(config_path: Path) -> int:
    rel = config_path.relative_to(ROOT)
    action = ask_choice(
        "What now?",
        [
            ("1", "Preview the plan (safe, no compute)"),
            ("2", "Run the pipeline now (live progress)"),
            ("3", "Just save the config and exit"),
        ],
        default="1",
    )
    if action == "1":
        print()
        return subprocess.call(
            [sys.executable, str(ROOT / "scripts" / "vermamg.py"), "plan", "--config", str(config_path)],
            cwd=str(ROOT),
        )
    if action == "2":
        return run_with_progress(config_path)
    print(f"\n  Saved. Later you can run it with:\n"
          f"    python scripts/vermamg_init.py --run {rel}        # live stage progress\n"
          f"    python scripts/vermamg.py run --config {rel} --resume --follow\n")
    return 0


def interactive_flow() -> int:
    a = questionnaire()
    cfg_dir = ROOT / "run_configs"
    cfg_dir.mkdir(exist_ok=True)
    config_path = cfg_dir / f"{a['project_slug']}_{a['run_label']}.yaml"
    config_path.write_text(build_config_text(a), encoding="utf-8")
    print(f"\n  Wrote config: {config_path.relative_to(ROOT)}")
    return offer_plan_or_run(config_path)


def template_flow() -> int:
    env = ask_choice(
        "Which environment is the template for?",
        [("1", "Local machine / WSL"), ("2", "HPC cluster (SLURM)")],
        default="1",
    )
    tpl = ROOT / TEMPLATES["local" if env == "1" else "slurm"]
    if not tpl.is_file():
        print(f"  ! Template not found: {tpl}")
        return 1
    name = slugify(ask("Config file name (without .yaml)", "my_project_run"))
    cfg_dir = ROOT / "run_configs"
    cfg_dir.mkdir(exist_ok=True)
    config_path = cfg_dir / f"{name}.yaml"
    if config_path.exists() and ask(f"{config_path.name} exists. Overwrite? (y/N)", "n").lower() not in ("y", "yes"):
        print("  Aborted (existing file kept).")
        return 0
    config_path.write_text(tpl.read_text(encoding="utf-8"), encoding="utf-8")
    rel = config_path.relative_to(ROOT)
    print(f"\n  Wrote a template to: {rel}")
    print("  Next:")
    print(f"    1) Open {rel} in your editor and fill every [FILL] field.")
    print("    2) Then run it (either way):")
    print(f"         python scripts/vermamg_init.py --run {rel}        # live stage progress")
    print(f"         python scripts/vermamg.py run --config {rel} --resume --follow")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="VermAMG setup wizard / launcher with live stage progress.")
    parser.add_argument("--run", metavar="CONFIG",
                        help="Run an existing config file with live stage progress (skip the questions).")
    args = parser.parse_args(argv)

    if args.run:
        config_path = Path(args.run)
        if not config_path.is_absolute():
            config_path = ROOT / config_path
        if not config_path.is_file():
            print(f"  ! Config not found: {args.run}")
            return 2
        return run_with_progress(config_path)

    how = ask_choice(
        "How would you like to configure VermAMG?",
        [
            ("1", "Interactive  - answer a few questions here in the terminal"),
            ("2", "Template     - write a config file to fill in your editor, then run"),
        ],
        default="1",
    )
    return interactive_flow() if how == "1" else template_flow()


if __name__ == "__main__":
    raise SystemExit(main())
