#!/usr/bin/env python3
"""Explicit-path M09D P2Rank local runner generator.

This generic helper is the run-directory-safe replacement for mode-specific
wrappers. In the first orchestrator slice it performs validation and can write
runner stubs plus a manifest; execution wiring is enabled in the next slice.
"""

from __future__ import annotations

import argparse
import csv
import stat
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--query-manifest", type=Path, required=True)
    parser.add_argument("--reference-manifest", type=Path, required=True)
    parser.add_argument("--p2rank-cmd", type=Path, required=True)
    parser.add_argument("--p2rank-jar", type=Path, required=True)
    parser.add_argument("--local-run-dir", type=Path, required=True)
    parser.add_argument("--query-out-root", type=Path, required=True)
    parser.add_argument("--reference-out-root", type=Path, required=True)
    parser.add_argument("--run-manifest", type=Path, required=True)
    parser.add_argument("--allowed-root", type=Path, required=True)
    parser.add_argument("--threads", type=int, default=4)
    parser.add_argument("--chunk-size", type=int, default=64)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def require_under(path: Path, root: Path) -> None:
    path_resolved = path.resolve()
    root_resolved = root.resolve()
    try:
        path_resolved.relative_to(root_resolved)
    except ValueError as exc:
        raise SystemExit(f"ERROR: refusing path outside allowed root: path={path} root={root}") from exc


def read_tsv(path: Path) -> list[dict[str, str]]:
    with path.open(errors="replace", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def require_columns(label: str, rows: list[dict[str, str]], cols: list[str]) -> None:
    if not rows:
        raise SystemExit(f"ERROR: {label} is empty: {rows}")
    missing = [col for col in cols if col not in rows[0]]
    if missing:
        raise SystemExit(f"ERROR: {label} missing required columns: {missing}")


def runner_stub(role: str, manifest: Path, out_root: Path) -> str:
    return f"""#!/usr/bin/env bash
set -euo pipefail
echo "VERMAMG_P2RANK_RUNNER_ROLE={role}"
echo "INPUT_MANIFEST={manifest}"
echo "OUT_ROOT={out_root}"
echo "STATUS=RUNNER_STUB_PENDING_EXECUTION_WIRING"
echo "This runner was generated by the generic explicit M09D helper."
echo "The full P2Rank execution body will be enabled after orchestrator plan review."
exit 3
"""


def write_runner(path: Path, text: str, overwrite: bool) -> None:
    if path.exists() and not overwrite:
        raise SystemExit(f"ERROR: runner exists; refusing overwrite: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def main() -> int:
    args = parse_args()
    for path in (args.local_run_dir, args.query_out_root, args.reference_out_root, args.run_manifest):
        require_under(path, args.allowed_root)
    for path in (args.query_manifest, args.reference_manifest, args.p2rank_cmd, args.p2rank_jar):
        if not path.exists():
            raise SystemExit(f"ERROR: required path missing: {path}")

    query_rows = read_tsv(args.query_manifest)
    ref_rows = read_tsv(args.reference_manifest)
    require_columns("query manifest", query_rows, ["query", "family", "query_model_pdb"])
    require_columns("reference manifest", ref_rows, ["unique_reference_id", "reference_layer", "target", "reference_file_path"])

    query_missing = [row for row in query_rows if not Path(row["query_model_pdb"]).exists()]
    ref_missing = [row for row in ref_rows if not Path(row["reference_file_path"]).exists()]
    print("VERMAMG_M09D_EXPLICIT_RUNNER_GENERATOR")
    print(f"query_rows\t{len(query_rows)}")
    print(f"reference_rows\t{len(ref_rows)}")
    print(f"query_missing_pdb\t{len(query_missing)}")
    print(f"reference_missing_pdb\t{len(ref_missing)}")
    print(f"threads\t{args.threads}")
    print(f"chunk_size\t{args.chunk_size}")
    print(f"write\t{'YES' if args.write else 'NO'}")
    if query_missing or ref_missing:
        print("validation_status\tBLOCKED_MISSING_INPUT_PDB")
        return 2
    if not args.write:
        print("validation_status\tDRY_RUN_OK")
        return 0

    query_runner = args.local_run_dir / "run_p2rank_query_models_local.sh"
    reference_runner = args.local_run_dir / "run_p2rank_reference_resolved_unique_local.sh"
    write_runner(query_runner, runner_stub("query", args.query_manifest, args.query_out_root), args.overwrite)
    write_runner(reference_runner, runner_stub("reference", args.reference_manifest, args.reference_out_root), args.overwrite)

    args.run_manifest.parent.mkdir(parents=True, exist_ok=True)
    with args.run_manifest.open("w", newline="") as handle:
        writer = csv.writer(handle, delimiter="\t", lineterminator="\n")
        writer.writerow(["runner_role", "runner_path", "input_manifest", "output_root", "input_rows", "status", "note"])
        writer.writerow(["query", str(query_runner), str(args.query_manifest), str(args.query_out_root), len(query_rows), "STUB_READY", "execution_body_pending_plan_review"])
        writer.writerow(["reference", str(reference_runner), str(args.reference_manifest), str(args.reference_out_root), len(ref_rows), "STUB_READY", "execution_body_pending_plan_review"])
    print(f"query_runner\t{query_runner}")
    print(f"reference_runner\t{reference_runner}")
    print(f"run_manifest\t{args.run_manifest}")
    print("validation_status\tPASS_STUB_RUNNERS_WRITTEN")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

